name: Main Nostalgia_Camp_Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  build_bot_and_push_to_docker_hub:
    name: Push bot to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_PRODUCTION }}
          password: ${{ secrets.DOCKER_PASSWORD_PRODUCTION }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./bot/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME_PRODUCTION }}/nostalgia_camp_bot-bot:latest

  build_gateway_and_push_to_docker_hub:
    name: Push gateway to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_PRODUCTION }}
          password: ${{ secrets.DOCKER_PASSWORD_PRODUCTION }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./gateway/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME_PRODUCTION }}/nostalgia_camp_bot-gateway:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs:
      - build_bot_and_push_to_docker_hub
      - build_gateway_and_push_to_docker_hub
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy docker-compose.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_PRODUCTION }}
        username: ${{ secrets.USER_PRODUCTION }}
        key: ${{ secrets.SSH_KEY_PRODUCTION }}
        passphrase: ${{ secrets.SSH_PASSPHRASE_PRODUCTION }}
        source: "docker-compose.production.yml"
        target: "Nostalgia_Camp_Bot"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PRODUCTION }}
        username: ${{ secrets.USER_PRODUCTION }}
        key: ${{ secrets.SSH_KEY_PRODUCTION }}
        passphrase: ${{ secrets.SSH_PASSPHRASE_PRODUCTION }}
        script: |
          cd Nostalgia_Camp_Bot
          docker compose -f docker-compose.production.yml down
          docker compose -f docker-compose.production.yml pull
          docker compose -f docker-compose.production.yml up -d

  send_message:
    name: Send Message
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Зафиксирован push в ${{ github.server_url }}/${{ github.repository }}

          Отчёт по push:

          ${{ github.actor }} запушил ${{ github.ref_name }}. Последний commit:

          "${{ github.event.head_commit.message }}"

          Ссылка на commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}

          Workflow выполнен успешно, включая следующее:
          - Running tests;
          - Pushing fresh images of repository to Dockerhub;
          - Deploying images to production server.

          Этот отчёт инициирован следующим workflow:
        
          ${{ github.workflow }}: ${{ github.server_url }}/${{ github.repository }}/.github/workflows/main.yml
